# Generated by Django 4.1.2 on 2023-03-25 14:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smssys', '0003_alter_myuser_address_alter_myuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicschoolyear',
            name='academicSchoolYearType',
        ),
        migrations.AddField(
            model_name='academicschoolyear',
            name='date_recorded',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='academicschoolyear',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='academicschoolyear',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AcademicSchoolYearType',
        ),
    ]
