# Generated by Django 4.1.2 on 2023-03-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smssys', '0004_remove_academicschoolyear_academicschoolyeartype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='academicYear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smssys.academicschoolyear'),
            preserve_default=False,
        ),
    ]
