# Generated by Django 4.1.2 on 2023-03-30 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smssys', '0005_schedule_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicschoolyear',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='isActive',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('scheduleClass', 'academicYear', 'subject')},
        ),
        migrations.CreateModel(
            name='StudentClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('statue', models.CharField(max_length=20)),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smssys.studentclass')),
            ],
        ),
    ]
