# Generated by Django 4.1.2 on 2023-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssys', '0007_alter_academicschoolyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodtype',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectclass',
            unique_together={('teacherClass', 'academicSchoolYear', 'subject')},
        ),
    ]
