# Generated by Django 4.1.2 on 2023-10-25 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import random


class Migration(migrations.Migration):

    dependencies = [
        ('smssys', '0009_rename_class_classbillingitems_billingclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stid',
            field=models.CharField(default=random.randrange(20, 50), max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentAttendent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendent', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('academicSemesterPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smssys.academicsemesterperiod')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smssys.studentclass')),
                ('teacherClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smssys.teachersubjectclass')),
            ],
        ),
    ]
